### ISSUE TITLE
TODO: All

### ISSUE THREAD

**Issue by sherubthakur** [sherubthakur/dotfiles-nixy#3]
- [ ] Setup Docker (engine/daemon) completely using nix config
- [ ] vim: coc-explorer
- [ ] vim: coc-actions
- [ ] vim: Fix error on startup with coc-* {eslint, json}
- [ ] tmux
